# Generated by Django 3.0.4 on 2020-04-06 12:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('paternidad', models.IntegerField(choices=[(0, 'No'), (1, 'Hijo'), (2, 'Proceso Admisión')], default=0)),
                ('paternidad_fecha', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('distincion', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Pastor Principal'), (2, 'Pastor Adjunto'), (3, 'Secretario'), (4, 'Líder'), (5, 'Miembro')], default=0)),
                ('baja_fecha', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('baja_motivo', models.IntegerField(choices=[(0, 'No'), (1, 'Sin Interés'), (2, 'Falleció'), (3, 'Ya no es pastor')], default=0, verbose_name='Motivo')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paises.Ciudad')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Móvil'), (2, 'Casa'), (3, 'Trabajo')], default=1)),
                ('whatsapp', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', related_query_name='telefono', to='pastores.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Matrimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esposa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esposa', related_query_name='esposa', to='pastores.Persona')),
                ('esposo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esposo', related_query_name='esposo', to='pastores.Persona')),
            ],
        ),
    ]
