# Generated by Django 3.0.4 on 2020-03-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('paternidad', models.IntegerField(choices=[(0, 'No'), (1, 'Hijo'), (2, 'Proceso Admisión')], default=0)),
                ('distincion', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Pastor Principal'), (2, 'Pastor Adjunto'), (3, 'Secretario'), (4, 'Líder'), (5, 'Miembro')], default=0)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paises.Ciudad')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Matrimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esposa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='esposa', related_query_name='esposa', to='pastores.Persona')),
                ('esposo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='esposo', related_query_name='esposo', to='pastores.Persona')),
            ],
        ),
    ]
