# Generated by Django 3.0.4 on 2020-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='baja_fecha',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='baja_motivo',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sin Interés'), (2, 'Fallescio'), (3, 'Ya no es pastor')], default=0),
        ),
    ]
