# Generated by Django 3.0.4 on 2020-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0002_auto_20200321_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='baja_fecha',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='baja_motivo',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sin Interés'), (2, 'Falleció'), (3, 'Ya no es pastor')], default=0),
        ),
    ]
