# Generated by Django 3.0.4 on 2020-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0003_auto_20200321_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='baja_fecha',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
