# Generated by Django 3.0.4 on 2020-03-21 20:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0005_auto_20200321_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
