# Generated by Django 3.0.4 on 2020-03-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0007_auto_20200321_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='baja_fecha',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='paternidad_fecha',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
