# Generated by Django 3.0.4 on 2020-03-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0008_auto_20200321_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
