# Generated by Django 3.0.4 on 2020-03-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0010_auto_20200325_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonio',
            name='esposa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esposa', related_query_name='esposa', to='pastores.Persona'),
        ),
        migrations.AlterField(
            model_name='matrimonio',
            name='esposo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esposo', related_query_name='esposo', to='pastores.Persona'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', related_query_name='telefono', to='pastores.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='matrimonio',
            unique_together={('esposo', 'esposa')},
        ),
    ]
