# Generated by Django 3.0.4 on 2020-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0012_auto_20200326_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonio',
            name='esposa',
        ),
        migrations.RemoveField(
            model_name='matrimonio',
            name='esposo',
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='esposos',
            field=models.ManyToManyField(related_name='matrimonios', to='pastores.Persona'),
        ),
    ]
