# Generated by Django 3.0.4 on 2020-03-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0013_auto_20200326_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonio',
            name='esposos',
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='esposa',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='esposa', related_query_name='esposa', to='pastores.Persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonio',
            name='esposo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='esposo', related_query_name='esposo', to='pastores.Persona'),
            preserve_default=False,
        ),
    ]
