# Generated by Django 3.0.4 on 2020-04-06 12:46

from django.db import migrations, models
import django.db.models.deletion
import informes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default=informes.models.periodo_actual)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscuelaSobrenatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default=informes.models.periodo_actual)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default=informes.models.periodo_actual)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Convencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default=informes.models.periodo_actual)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default=informes.models.periodo_actual)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
