# Generated by Django 3.0.4 on 2020-03-23 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesias', '0003_auto_20200323_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscuelaSobrenatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Convencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('respuesta', models.IntegerField(choices=[(0, 'No Informado'), (1, 'Si'), (2, 'No'), (3, 'Duda')], default=0)),
                ('observacion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iglesias.Iglesia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
