# Generated by Django 3.0.4 on 2020-04-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastores', '0001_initial'),
        ('paises', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paises.Ciudad')),
                ('pastor', models.ForeignKey(limit_choices_to={'distincion': 1, 'esposa': None}, null=True, on_delete=django.db.models.deletion.PROTECT, to='pastores.Persona')),
            ],
            options={
                'verbose_name': 'Iglesia',
                'verbose_name_plural': 'Iglesias',
            },
        ),
    ]
