# Generated by Django 3.0.4 on 2020-03-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0001_initial'),
        ('pastores', '0007_auto_20200321_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=150)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paises.Ciudad')),
                ('pastor', models.ForeignKey(limit_choices_to={'distincion': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, to='pastores.Persona')),
            ],
        ),
    ]
