# Generated by Django 3.0.4 on 2020-03-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglesia',
            name='direccion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
