# Generated by Django 3.0.4 on 2020-03-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0003_auto_20200323_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglesia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
